# Exercise 6: Weather anomalies (10 points)

The aim of this exercise is to analyze historical weather data.
- In Problem 1 you read in a tricky data file and explore it's contents.
- In problem 2, you will convert and aggregate the data from daily temperatures in Fahrenheit, to monthly average temperatures in Celsius.
- In Problem 3, you will finally analyze weather anomalies by comparing monthly average temperatures to a long-term average.

### Tips for completing this exercise

- Use **exactly** the same variable names as in the instructions because your answers will be automatically graded, and the tests that grade your answers rely on following the same formatting or variable naming as in the instructions.
- **Please do not**:

    - **Change the file names**. Do all of your editing in the provided `Exercise-6-problems-1-3.ipynb` file (this file).
    - **Copy/paste cells in this notebook**. We use an automated grading system that will fail if there are copies of code cells.
    - **Change the existing cell types**. You can add cells, but changing the cell types for existing cells (from code to markdown, for example) will also cause the automated grader to fail.

In [15]:
# Assertions - checks that the values within the code are suitable for the function
# For example here, we want to make sure that speed is not negative

def convert_kph_ms(speed):
    """Converts velocity (speed) in km/hr to m/s"""
    # here you provide an assert rule, make sure to give information for the error
    assert (type(speed) == int or type(speed) == float), "Wind speed values must be numbers"
    assert speed <= 408.0, "Wind speed exceeds fastest winds ever measured"
    assert speed >= 0.0, "Wind speed values must be positive or zero"
    return speed * 1000 / 3600

wind_speed_km = 10 # here, if you put a negative, it will give you an AssertionError
wind_speed_ms = convert_kph_ms(wind_speed_km)

print(f"A wind speed of {wind_speed_km} km/hr is {wind_speed_ms} m/s.")

# The format of the assertion error should be as follows: 
# assert <some condition>, "Error message to display"
# NOTE: the order is important here, first specify that it has to be a number, and then that it has to be positive

A wind speed of 10 km/hr is 2.7777777777777777 m/s.

## AI tool usage agreement

**Enter your name (and that of your partner) in the cell below** to confirm that you have followed the [course guidelines on the use of AI tools](https://geo-python-site.readthedocs.io/en/latest/course-info/ai-tools.html) and understand that misuse of AI tools is considered cheating.

YOUR ANSWER HERE

## Problem 1 - Reading in a tricky data file (2 points)

You first task for this exercise is to read in the data file [data/1091402.txt](data/1091402.txt) to a variable called `data`. Pay attention to the input data structure and no data values.

### Scores for this problem

**Your score on this problem will be based on following criteria:**

- Reading the data into a variable called `data` using pandas
    - Skipping the second row of the datafile that contains `----------` characters that don't belong to the data
    - Convert the no-data values (`-9999`) into `NaN` 
- Calculating basic statistics from the data
- Including comments that explain what most lines in the code do

### Part 1 (1 point)

You should start by loading the data file.

- Read the data file into variable the variable `data`
    - Skip the second row
    - Convert the no-data values (`-9999`) into `NaN`

In [16]:
!pip install pandas # to install the library if it is not available

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from pandas) (2025.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 5.9 MB/s  0:00:02 eta 0:00:01
Downloading numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 13.1 MB/s  0:00:01m0:00:0100:01
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]2m2/3 [pandas]
Successfully installed numpy-2.2.6 pandas-2.3.3 tzdata-2025.3

In [17]:
import pandas as pd

In [72]:
# define a path: 
fp = r"data/1091402.txt" # r here tells NOT treat / as special characters
# Or you can put the path instead of fp inside the read_csv function (note without the r)
data = pd.read_csv(fp, 
                   # criteria for what becomes an NA:
                   na_values=["-","*","***","-9999"], 
                   # Separation with white space:
                   sep=r"\s+", 
                   # Skip second row (i.e., 1)
                   skiprows=[1],
                   # note that the header is present:
                   header = 0)

#data = data.drop()

In [96]:
data.head(15)

,STATION,ELEVATION,LATITUDE,LONGITUDE,DATE,PRCP,TAVG,TMAX,TMIN
0,GHCND:FIE00142080,51,60.3269,24.9603,19520101,0.31,37.0,39.0,34.0
1,GHCND:FIE00142080,51,60.3269,24.9603,19520102,NaN,35.0,37.0,34.0
2,GHCND:FIE00142080,51,60.3269,24.9603,19520103,0.14,33.0,36.0,NaN
3,GHCND:FIE00142080,51,60.3269,24.9603,19520104,0.05,29.0,30.0,25.0
4,GHCND:FIE00142080,51,60.3269,24.9603,19520105,0.06,27.0,30.0,25.0
5,GHCND:FIE00142080,51,60.3269,24.9603,19520106,NaN,26.0,36.0,NaN
6,GHCND:FIE00142080,51,60.3269,24.9603,19520107,0.03,39.0,43.0,32.0
7,GHCND:FIE00142080,51,60.3269,24.9603,19520108,NaN,33.0,41.0,30.0
8,GHCND:FIE00142080,51,60.3269,24.9603,19520109,0.18,38.0,39.0,32.0
9,GHCND:FIE00142080,51,60.3269,24.9603,19520111,0.10,33.0,36.0,NaN
10,GHCND:FIE00142080,51,60.3269,24.9603,19520112,0.28,29.0,32.0,NaN
11,GHCND:FIE00142080,51,60.3269,24.9603,19520114,NaN,18.0,21.0,NaN
12,GHCND:FIE00142080,51,60.3269,24.9603,19520115,0.06,28.0,30.0,16.0
13,GHCND:FIE00142080,51,60.3269,24.9603,19520116,0.63,35.0,NaN,28.0
14,GHCND:FIE00142080,51,60.3269,24.9603,19520117,NaN,29.0,34.0,NaN

In [73]:
# Check that the dataframe looks ok:
data.head()

,STATION,ELEVATION,LATITUDE,LONGITUDE,DATE,PRCP,TAVG,TMAX,TMIN
0,GHCND:FIE00142080,51,60.3269,24.9603,19520101,0.31,37.0,39.0,34.0
1,GHCND:FIE00142080,51,60.3269,24.9603,19520102,NaN,35.0,37.0,34.0
2,GHCND:FIE00142080,51,60.3269,24.9603,19520103,0.14,33.0,36.0,NaN
3,GHCND:FIE00142080,51,60.3269,24.9603,19520104,0.05,29.0,30.0,25.0
4,GHCND:FIE00142080,51,60.3269,24.9603,19520105,0.06,27.0,30.0,25.0

In [84]:
# Check the last rows of the data (there should be some NaN values)
data.tail()

,STATION,ELEVATION,LATITUDE,LONGITUDE,DATE,PRCP,TAVG,TMAX,TMIN
23711,GHCND:FIE00142080,51,60.3269,24.9603,20170930,NaN,47.0,49.0,44.0
23712,GHCND:FIE00142080,51,60.3269,24.9603,20171001,0.04,47.0,48.0,45.0
23713,GHCND:FIE00142080,51,60.3269,24.9603,20171002,NaN,47.0,49.0,46.0
23714,GHCND:FIE00142080,51,60.3269,24.9603,20171003,0.94,47.0,NaN,44.0
23715,GHCND:FIE00142080,51,60.3269,24.9603,20171004,0.51,52.0,56.0,NaN

### Part 2 (1 point)

In this section, you will calculate some basic statistics of the input data.

- Calculate how many no-data (NaN) values there are in the `TAVG` column
    - Assign your answer to a variable called `tavg_nodata_count`

In [88]:
#tavg_nodata_count = data[data["TAVG"].isna()]
tavg_nodata_count = len(data[data["TAVG"].isna()])
tavg_nodata_count

3308

In [89]:
# Print out the solution:
print(f'Number of no-data values in column "TAVG": {tavg_nodata_count}')

Number of no-data values in column "TAVG": 3308

- Calculate how many no-data (NaN) values there are for the `TMIN` column
    - Assign your answer into a variable called `tmin_nodata_count`

In [94]:
tmin_nodata_count = len(data[data["TMIN"].isna()])
tmin_nodata_count

365

In [95]:
# Print out the solution:
print(f'Number of no-data values in column "TMIN": {tmin_nodata_count}')

Number of no-data values in column "TMIN": 365

- Calculate the total number of days covered by this data file
    - Assign your answer into a variable called `day_count`

In [119]:
day_count = data["DATE"].nunique()

In [120]:
# Print out the solution:
print(f'Number of days: {day_count}')

Number of days: 23716

- Find the date of the oldest (first) observation
    - Assign your answer into a variable called `first_obs`

In [104]:
first_obs = min(data["DATE"])
first_obs = data["DATE"].min()

In [105]:
# Print out the solution:
print(f'Date of the first observation: {first_obs}')

Date of the first observation: 19520101

- Find the date of the most recent (last) observation
    - Assign your answer into a variable called `last_obs`

In [117]:
#last_obs = max(data["DATE"])
last_obs = data["DATE"].max()

In [116]:
# Print out the solution:
print(f'Date of the last observation: {last_obs}')

Date of the last observation: 20171004

- Find the average temperature for the whole data file (all observtions) from column `TAVG`
    - Assign your answer into a variable called `avg_temp`

In [111]:
avg_temp = data["DATE"].mean()

np.float64(19847916.06278462)

In [118]:
# Print out the solution:
print(f'Average temperature (F) for the whole dataset: {round(avg_temp, 2)}')

Average temperature (F) for the whole dataset: 19847916.06

- Find the average `TMAX` temperature over the [Summer of '69](https://www.youtube.com/watch?v=9f06QZCVUHg) (months May, June, July, and August of the year 1969)
    - Assign your answer into a variable called `avg_temp_1969`

In [128]:
Y_1969 = data[(data["DATE"] >= 19690501) & (data["DATE"] <= 19690831)]
avg_temp_1969 = Y_1969["TMAX"].mean()

In [129]:
# This test print should print a number
print(f"Average temperature (F) for the Summer of '69: {round(avg_temp_1969, 2)}")

Average temperature (F) for the Summer of '69: 67.82

## Problem 2 - Calculating monthly average temperatures (3 points)

For this problem your goal is to calculate monthly average temperatures in degrees Celsius from the daily Fahrenheit values we have in the data file. You can continue working with the same DataFrame that you used in Problem 1.

### Scores for this problem

**Your score on this problem will be based on following criteria:**

- Calculating the monthly average temperatures in degrees Celsius for the each month in the dataset (i.e., for each month of each year)
    - You should store the monthly average temperatures in a new Pandas DataFrame called `monthly_data`
    - `monthly_data` should contain a new column called `temp_celsius` the monthly average temperatures in Celsius
    - Convert the `TAVG` values in Fahrenheit into Celsius and store the output in the `temp_celsius`
- Including comments that explain what most lines in the code do

**Hint**: *You can start by creating a new column with a label for each year and month, and then continue grouping the data based on this information.*

In [150]:
# define calcius to fahrengheit function:
def celcius_to_fahr(temp):
    f_temp = 9/5 * temp +32
    return f_temp

# Convert the temperature from Celsius to Fahrenheit:    
data["TAVG_fahr"] = celcius_to_fahr(data["TAVG"])

# Create year, month, day columns:
data["YEAR"] = data["DATE"] // 10000        # get first 4 digits
data["MONTH"] = (data["DATE"] // 100) % 100  # get middle 2 digits
data["DAY"] = data["DATE"] % 100            # get last 2 digits
data.tail(15) 

# Group data by month:
grouped = data.groupby(by="MONTH")
monthly_data = grouped["TAVG_fahr"].mean()

#monthly_data = monthly_data.rename(columns={"TEMP_C": "MAX_C"})

In [147]:
# This test prints the length of variable monthly_data
print(len(monthly_data))

12

In [148]:
# This test prints the column names of monthly_data
print(monthly_data.columns.values)

AttributeError: 'Series' object has no attribute 'columns'

In [ ]:
# This test prints the mean of temp_celsius
print(monthly_data['temp_celsius'].mean())

In [ ]:
# This test prints the median of temp_celsius
print(round(monthly_data['temp_celsius'].median(), 2))

## Problem 3 - Calculating temperature anomalies (5 points)

Our goal in this problem is to calculate monthly temperature anomalies in order to see how temperatures have changed over time, relative to an observation period between 1952-1980. You can continue working with the same data that you used in Problems 1 and 2.

**Your score on this problem will be based on following criteria:**

### Part 1

- Calculating ***the average (mean) temperature for each month (e.g., January, February, March, ...) over the period from 1952 up to and including 1980*** in a new DataFrame called `reference_temps`
    - You should end up with 12 values, 1 mean temperature for each month during the time period (see example table and figure below).
    - The columns in the new DataFrame should be `month` and `ref_temp`
    
Your `reference_temps` dataframe should have the following structure: 1 value for each month of the year (12 total) and the values represent and average in the observation period 1952-1980. The `ref_temp` temperatures should be in degrees Celsius.
   
| month    | ref_temp         |
|----------|------------------|
| 01       | -5.838761        |
| 02       | -7.064088        |
| 03       | -3.874213        |
| ...      | ...              |

### Part 2

- Calculating **a temperature anomaly for every month** in the `monthly_data` DataFrame using the corresponding monthly average temperature for each of the 12 months:
    - In order to achieve this you need to make **a table join** (see [hints for this week](https://geo-python-site.readthedocs.io/en/develop/lessons/L6/exercise-6.html#joining-data-from-one-dataframe-to-another)) between `monthly_data` and `ref_temps` based on the month.
    - The temperature anomaly is calculated as the difference between the temperature for a given month (`temp_celsius` column in `monthly_data`) and the corresponding monthly reference temperature (`ref_temp` column in`reference_temps`).
    - Store the result in a new column `"diff"` 
    
As the output of the table join and the calculation, you should have three new columns in the `monthly_data` DataFrame:

1. `diff`: The temperature anomaly, i.e. the difference between the temperature for a given month (e.g., February 1960) and the mean temperature during the reference period (e.g., the average of all Februaries between 1952 and 1980), 
2. `month`: The month for that row of observations
3. `ref_temp`: The monthly reference temperature

A summary of the relationships between the `monthly_data` and `reference_temps` DataFrames, as well as how the `diff` value should be calculated in the `monthly_data` DataFrame is presented in the figure below.

![Exercise 6 dataframes](img/exercise-6-dataframes.png)<br/>
*Figure 1. Relationships between the `monthly_data` and `reference_temps` DataFrames.*

You should finally report which month had the greatest weather anomaly during the observed time period.

Remember to include comments in your code.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# Check the monthly data:
monthly_data.head()

In [ ]:
# Print out desriptive statistics for the relevant columns:
monthly_data[["temp_celsius", "ref_temp", "diff"]].describe()

Remember also to calculate which month had the largest temperature anomaly during the observed time period in comparison with the reference data. Use the cell below to calculate and print out the answers. Note, you may want to consider the largest absolute value of the temperature anomaly, as well as the largest positive and negative anomalies.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

## Part 3 (*optional*) - **AI-LLM OK**

Using [ChatGPT](https://openai.com/chatgpt), calculate the reference temperatures and temperature anomalies as directed above.

- Your reference temperatures should be stored in a new DataFrame called `ai_reference_temps`
    - The columns in the new DataFrame should be `month` and `ai_ref_temp`
- Calculate **a temperature anomaly for every month** in the `monthly_data` DataFrame using the corresponding monthly average temperature for each of the 12 months:
    - You again need to make **a table join** (see [hints for this week](https://geo-python-site.readthedocs.io/en/develop/lessons/L6/exercise-6.html#joining-data-from-one-dataframe-to-another)) between `monthly_data` and `ai_ref_temps` based on the month.
    - The temperature anomaly is calculated as the difference between the temperature for a given month (`temp_celsius` column in `monthly_data`) and the corresponding monthly reference temperature (`ai_ref_temp` column in`reference_temps`).
    - Store the result in a new column `"ai_diff"` 

In order to do this, you should post both the prompt you provide to ChatGPT and the code it produces in the cells below. As your prompts may need to be refined to get your code working, please report each prompt so we can see how you arrived at your final version of the function.

### Prompt 1

Enter the text of the first prompt you used for this part of the exercise below.

YOUR ANSWER HERE

Enter the code generated by your first prompt below.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

Looking at the function produced by ChatGPT do you see any problems compared to your solution in Part 1? Please comment below about this.

YOUR ANSWER HERE

Test out your code by running the tests below.

In [ ]:
# Check the monthly data:
monthly_data.head()

In [ ]:
# Print out desriptive statistics for the relevant columns:
monthly_data[["temp_celsius", "ai_ref_temp", "ai_diff"]].describe()

### Additional prompts

In the event your code does not pass all of the tests above, please enter the prompt(s) you used to refine the function in the cell below. If you used more than one prompt, you can format them as a Markdown list using the format demonstrated below:

```
1. First prompt
2. Second prompt
3. ...
```

If no additional prompts were needed, you can skip this.

YOUR ANSWER HERE

Enter the final version of your code produced by ChatGPT in the cell below. You can test the code by re-running the tests above after updating the code below.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

Does your revised function now pass all of the tests?
- If yes, please comment below about your experience using ChatGPT and the benefits and drawbacks you see.
- If no, what kinds of problems do you see with the revised function produced by ChatGPT compared to your solution in Part 1? Please comment below about this.

YOUR ANSWER HERE

### Final comments

If you have any other comments about your experience using ChatGPT in this problem, please enter those below.

YOUR ANSWER HERE